title: IDI-FLY-V3 API
description: Hybrid API for Mission Telemetry

remote_theme: just-the-docs/just-the-docs@v0.8.2

color_scheme: dark

mermaid:
  version: "10.6.0"

search_enabled: true
heading_anchors: true
back_to_top: true

aux_links:
  GitHub: https://github.com/Idroneimages-LTD/IDI-FLY-DASHBOARD-V3
aux_links_new_tab: true

footer_content: "IDI-FLY-V3 API Documentation &copy; 2025"

nav_enabled: true

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green

plugins:
  - jekyll-remote-theme

markdown: kramdown
